const modelos=[
 {id:'muse',nome:'Muse',tag:'Editorial minimal',cat:'minimal',preco:39,cor:'#e7e1d5',accent:'#171717',ink:'#171717',imgs:['photo-1494790108377-be9c29b29330','photo-1517841905240-472988babdf9','photo-1487412720507-e7ab37603c6f'],desc:'Elegância editorial, tipografia marcante e bastante respiro para o conteúdo falar por você.'},
 {id:'glow',nome:'Glow',tag:'Beauty & skincare',cat:'beauty',preco:49,cor:'#ffb5d0',accent:'#ff315f',ink:'#401128',imgs:['photo-1524504388940-b1c1722653e1','photo-1488426862026-3ee34a7d66df','photo-1531123897727-8f129e1688ce'],desc:'Um universo rosa, luminoso e delicado para creators de beleza, maquiagem e skincare.'},
 {id:'pulse',nome:'Pulse',tag:'Fashion statement',cat:'fashion',preco:49,cor:'#ff6640',accent:'#ffdb00',ink:'#260900',imgs:['photo-1534528741775-53994a69daeb','photo-1529139574466-a303027c1d8b','photo-1502823403499-6ccfcf4fb453'],desc:'Cor, movimento e tipografia sem timidez para um portfólio impossível de ignorar.'},
 {id:'bloom',nome:'Bloom',tag:'Natural lifestyle',cat:'lifestyle',preco:39,cor:'#bddd9f',accent:'#24482a',ink:'#17311c',imgs:['photo-1508214751196-bcfd4ca60f91','photo-1487412720507-e7ab37603c6f','photo-1544005313-94ddf0286df2'],desc:'Natural e acolhedor, perfeito para conteúdos de rotina, bem-estar e vida real.'},
 {id:'noir',nome:'Noir',tag:'Dark premium',cat:'minimal',preco:59,cor:'#17151a',accent:'#d8ff45',ink:'#f8f4ea',imgs:['photo-1544005313-94ddf0286df2','photo-1548142813-c348350df52b','photo-1531123897727-8f129e1688ce'],desc:'Contraste cinematográfico e acabamento premium para trabalhos de alto impacto.'},
 {id:'splash',nome:'Splash',tag:'Color pop',cat:'fashion',preco:49,cor:'#7657ff',accent:'#ffdd57',ink:'#fff',imgs:['photo-1529139574466-a303027c1d8b','photo-1502823403499-6ccfcf4fb453','photo-1534528741775-53994a69daeb'],desc:'Jovem, vibrante e divertido — desenhado para prender a atenção desde o primeiro segundo.'}
];
const u=(id,w=900)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=86`;
const lista=document.querySelector('#modelos-lista'),dialog=document.querySelector('#preview-dialog');
function card(m,i){return `<article class="modelo" style="--card:${m.cor};--card-ink:${m.ink};--accent:${m.accent}" data-id="${m.id}" tabindex="0" role="button" aria-label="Ver demonstração do modelo ${m.nome}"><div class="produto-cover"><span class="cover-index">0${i+1}</span><span class="cover-tag">${m.tag}</span><div class="cover-browser"><div class="mini-bar"><i></i><i></i><i></i></div><img src="${u(m.imgs[0])}" alt="Capa do modelo ${m.nome}" loading="lazy"><div class="browser-copy"><small>UGC CREATOR</small><strong>${m.nome}</strong></div></div><div class="cover-phone"><img src="${u(m.imgs[1],500)}" alt="Versão móvel do modelo ${m.nome}" loading="lazy"><span>▶</span></div><span class="cover-note">SITE + MOBILE</span></div><div class="modelo-copy"><div><p>${m.tag}</p><h3>${m.nome}</h3></div><div class="price"><small>A partir de</small><strong>€${m.preco}</strong></div></div><button class="ver-demo" tabindex="-1">Explorar modelo <span>↗</span></button></article>`}
function render(filtro='todos'){const items=modelos.filter(m=>filtro==='todos'||m.cat===filtro);lista.innerHTML=items.map((m,i)=>card(m,i)).join('');lista.querySelectorAll('.modelo').forEach(el=>{const open=()=>abrir(modelos.find(m=>m.id===el.dataset.id));el.onclick=open;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}}})}
function screen(m,n){if(n===0)return `<div class="demo-page" style="--demo:${m.cor};--demo-ink:${m.ink};--demo-accent:${m.accent}"><nav><b>${m.nome}</b><span>TRABALHOS · SOBRE · CONTATO</span></nav><div class="demo-cover"><img src="${u(m.imgs[0],1000)}" alt="Criadora do modelo ${m.nome}"><div><small>UGC CREATOR</small><h3>Conteúdo que<br>parece <em>real.</em></h3><p>Estratégia, estética e conexão para marcas que querem ser lembradas.</p></div></div></div>`;if(n===1)return `<div class="demo-page works" style="--demo:${m.cor};--demo-ink:${m.ink};--demo-accent:${m.accent}"><header><small>MEUS TRABALHOS</small><h3>Conteúdo em<br><em>movimento.</em></h3></header><div class="video-row">${m.imgs.map((x,i)=>`<div><img src="${u(x,500)}" alt="Trabalho ${i+1}"><span>▶</span></div>`).join('')}</div><div class="marquee">BEAUTY ✦ LIFESTYLE ✦ FASHION ✦ UGC ✦</div></div>`;return `<div class="demo-page about" style="--demo:${m.cor};--demo-ink:${m.ink};--demo-accent:${m.accent}"><div class="about-grid"><img src="${u(m.imgs[2],700)}" alt="Foto sobre a criadora"><div><small>SOBRE MIM</small><h3>Oi, eu sou<br><em>a Maya.</em></h3><p>Transformo ideias em histórias visuais que aproximam pessoas e marcas.</p><button>Vamos criar juntas →</button></div></div><div class="services"><span>01 REELS</span><span>02 FOTOS</span><span>03 UNBOXING</span></div></div>`}
function abrir(m){document.querySelector('#preview-title').textContent=m.nome;document.querySelector('#preview-price').textContent=`€${m.preco}`;document.querySelector('#preview-desc').textContent=m.desc;document.querySelector('.escolher').dataset.modelo=m.id;const main=document.querySelector('#main-preview'),thumbs=document.querySelector('#preview-thumbs');main.innerHTML=screen(m,0);thumbs.innerHTML=[0,1,2].map(n=>`<button class="${n===0?'ativo':''}" data-screen="${n}" aria-label="Ver tela ${n+1}">${screen(m,n)}</button>`).join('');thumbs.querySelectorAll('button').forEach(b=>b.onclick=()=>{thumbs.querySelector('.ativo')?.classList.remove('ativo');b.classList.add('ativo');main.innerHTML=screen(m,+b.dataset.screen)});dialog.showModal();document.body.style.overflow='hidden'}
function fechar(){dialog.close();document.body.style.overflow=''}
document.querySelector('.fechar').onclick=fechar;dialog.addEventListener('click',e=>{if(e.target===dialog)fechar()});document.querySelectorAll('.filtros button').forEach(b=>b.onclick=()=>{document.querySelector('.filtros .ativo')?.classList.remove('ativo');b.classList.add('ativo');render(b.dataset.filter)});document.querySelector('.escolher').onclick=e=>location.href=`admin.html?modelo=${encodeURIComponent(e.currentTarget.dataset.modelo)}`;if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));render();
