const modelos=[
 {id:'muse',nome:'Muse',cat:'minimal',preco:39,cor:'#ebe8df',ink:'#171717',img:'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=85',img2:'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=700&q=80',desc:'Editorial, elegante e com bastante respiro.'},
 {id:'glow',nome:'Glow',cat:'beauty',preco:49,cor:'#ffbdd7',ink:'#401128',img:'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=85',img2:'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=700&q=80',desc:'Beauty e skincare com presença suave e luminosa.'},
 {id:'pulse',nome:'Pulse',cat:'fashion',preco:49,cor:'#ff5d36',ink:'#240902',img:'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=85',img2:'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=700&q=80',desc:'Cores fortes, tipografia grande e atitude fashion.'},
 {id:'bloom',nome:'Bloom',cat:'lifestyle',preco:39,cor:'#bfe7c4',ink:'#12311c',img:'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=900&q=85',img2:'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=700&q=80',desc:'Natural, acolhedor e perfeito para rotina e bem-estar.'},
 {id:'noir',nome:'Noir',cat:'minimal',preco:59,cor:'#171717',ink:'#f5f1e8',img:'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=900&q=85',img2:'https://images.unsplash.com/photo-1548142813-c348350df52b?auto=format&fit=crop&w=700&q=80',desc:'Impacto cinematográfico para trabalhos premium.'},
 {id:'splash',nome:'Splash',cat:'fashion',preco:49,cor:'#7456ff',ink:'#fff',img:'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=85',img2:'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?auto=format&fit=crop&w=700&q=80',desc:'Jovem, divertido e feito para prender a atenção.'}
];
const lista=document.querySelector('#modelos-lista'),dialog=document.querySelector('#preview-dialog');
function render(filtro='todos'){lista.innerHTML='';modelos.filter(m=>filtro==='todos'||m.cat===filtro).forEach(m=>{const b=document.createElement('button');b.className='modelo';b.style.setProperty('--card',m.cor);b.style.setProperty('--card-ink',m.ink);b.innerHTML=`<div class="modelo-media"><img src="${m.img}" alt="Demonstração do modelo ${m.nome}" loading="lazy"></div><div class="modelo-copy"><div class="modelo-top"><h3>${m.nome}</h3><small>€${m.preco}</small></div><p>${m.desc}</p></div>`;b.onclick=()=>abrir(m);lista.appendChild(b)})}
function abrir(m){document.querySelector('#preview-title').textContent=m.nome;document.querySelector('#preview-desc').textContent=m.desc;document.querySelector('.escolher').dataset.modelo=m.id;document.querySelector('#phone-preview').innerHTML=`<section class="demo-hero" style="background-image:url('${m.img}')"><small>UGC CREATOR</small><h3>Hi, I'm Maya.</h3><p>Conteúdo que aproxima marcas de pessoas.</p></section><div class="demo-grid"><img src="${m.img2}" alt="Foto de exemplo"><img src="${m.img}" alt="Foto de exemplo"></div><div class="demo-video"><img src="${m.img2}" alt="Prévia de vídeo vertical"></div>`;dialog.showModal();document.body.style.overflow='hidden'}
document.querySelector('.fechar').onclick=()=>{dialog.close();document.body.style.overflow=''};
dialog.addEventListener('click',e=>{if(e.target===dialog){dialog.close();document.body.style.overflow=''}});
document.querySelectorAll('.filtros button').forEach(b=>b.onclick=()=>{document.querySelector('.filtros .ativo').classList.remove('ativo');b.classList.add('ativo');render(b.dataset.filter)});
document.querySelector('.escolher').onclick=e=>{window.location.href=`admin.html?modelo=${encodeURIComponent(e.currentTarget.dataset.modelo)}`};
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));
render();
